### ISSUE TITLE
wiki: ZFS-Module-Parameters

### ISSUE THREAD

**Issue by gmelikov** [richardelling/zfs-linux-tools#1]
https://github.com/richardelling/zfs-linux-tools/wiki/ZFS-Module-Parameters

The main idea of this page is great! I have one question about it's future changing: did you generated it or created manually? What's about reworking man ZFS-Module-Parameters to generate such page (or only part with parameters)? @richardelling What do you think about it?

`man2html` can generate a good quality HTML code, which can be added to wiki https://jsfiddle.net/gmelikov/gsqo7n8d/

**Comment by richardelling** [comment]
man pages are far too tedious to deal with and they do not scale well. We'll use the web as it is intended. To that end, I've updated the index and tags cross references.

**Comment by gmelikov** [comment]
I don't like to have 2 different places with nearly the same information to update. But I'm afraid that you're right and it's the only way to have minimal needed info (man page) and well-documented one (wiki).
